/*!
 * @file motorControl.ino
 * @brief Example for N20 DC motor control.
 * @details This example drives the motor forward and backward with different speeds,
 * @n then stops.
 * @copyright Copyright (c) 2026 DFRobot Co.Ltd (http://www.dfrobot.com)
 * @license The MIT License (MIT)
 * @author JiaLi(zhixin.liu@dfrobot.com)
 * @version V1.0.0
 * @date 2026-05-09
 * @url https://github.com/DFRobot/DFRobot_N20Motor
 */

#include "DFRobot_N20Motor.h"

#if defined(ESP32)
#define N20_INA_PWM_PIN D5
#define N20_INB_PWM_PIN D6
#else
#define N20_INA_PWM_PIN 5
#define N20_INB_PWM_PIN 6
#endif
/**
 * note:
 * - The N20 motor requires a PWM signal to control its speed.
 * - The PWM signal is generated by the Arduino's PWM pins,It cannot be driven using digital pins.
*/

DFRobot_N20Motor motor(N20_INA_PWM_PIN, N20_INB_PWM_PIN);

void setup()
{
  Serial.begin(115200);
  delay(100);

  Serial.println();
  Serial.println(F("========================================"));
  Serial.println(F("  DFRobot N20 Motor"));
  Serial.println(F("  Motor Control Example"));
  Serial.println(F("========================================"));

  if (!motor.begin()) {
    Serial.println(F("[ERROR] Motor init failed, check pin configuration."));
    while (1) {
      delay(100);
    }
  }

  Serial.print(F("[OK] Motor initialized (INA PWM: "));
  Serial.print(N20_INA_PWM_PIN);
  Serial.print(F(", INB PWM: "));
  Serial.print(N20_INB_PWM_PIN);
  Serial.println(F(")"));
  Serial.println(F("Starting speed control loop..."));
  Serial.println();
}

void loop()
{
  Serial.println(F("-> Speed 255"));
  motor.setSpeed(255);
  delay(2000);

  Serial.println(F("-> Speed 150"));
  motor.setSpeed(150);
  delay(2000);

  Serial.println(F("-> Speed -255"));
  motor.setSpeed(-255);
  delay(2000);

  Serial.println(F("-> Speed 0"));
  motor.setSpeed(0);
  delay(2000);

  Serial.println();
}
