name=DFRobot_N20Motor
version=1.0.0
author=DFRobot
maintainer=JiaLi <zhixin.liu@dfrobot.com>
sentence=N20 DC motor Arduino library (SKU:DFR1276).
paragraph=Control N20 DC motor direction and speed by dual PWM output, including setSpeed API.
category=Device Control
url=https://github.com/DFRobot/DFRobot_N20Motor
architectures=*
