name=DFRobot_N20Motor
version=1.0.0
author=DFRobot
maintainer=DFRobot <support@dfrobot.com>
sentence=N20 DC motor Arduino library (SKU:DFR1277).
paragraph=Control N20 DC motor direction and speed by dual PWM output, including forward, backward, brake and stop APIs.
category=Device Control
url=https://github.com/DFRobot/DFRobot_N20Motor
architectures=*
